version: '2.1'

services:
  send-letter-service:
    extends:
      file: docker-compose-core.yml
      service: service
    depends_on:
      send-letter-database:
        condition: service_healthy
  send-letter-database:
    extends:
      file: docker-compose-core.yml
      service: database
    volumes:
      - send-letter-database-data:/var/lib/postgresql/data

volumes:
  send-letter-database-data:
