spring:
  application:
    name: Send Letter Service
  datasource:
      url: jdbc:tc:postgresql:9.6://localhost/letter_tracking
      driverClassName: org.testcontainers.jdbc.ContainerDatabaseDriver
      properties:
        charSet: UTF-8
      maxWaitForConnection: 1
      minSize: 8
      maxSize: 32
      evictionInterval: 10
      minIdleTime: 1 minute
      checkConnectionWhileIdle: true
      checkConnectionOnReturn: true
      removeAbandoned: true
      removeAbandonedTimeout: 60
      abandonWhenPercentageFull: 0
      testOnBorrow: true
      validationQuery: SELECT 1
#  jpa:
#    # Because detection is disabled you have to set correct dialect by hand.
#    database-platform: org.hibernate.dialect.PostgreSQL9Dialect
#    properties:
#      hibernate:
#        temp:
#          # Disable feature detection by this undocumented parameter.
#          # Check the org.hibernate.engine.jdbc.internal.JdbcServiceImpl.configure method for more details.
#          use_jdbc_metadata_defaults: false

# just another section to supposingly "silence" the 'wall-of-text' thing
#  jpa:
#    properties:
#      hibernate:
#        jdbc:
#          lob:
#            non_contextual_creation: true

ftp:
  hostname: localhost
  port: 46043
  target-folder: letters
  smoke-test-target-folder: ${FTP_SMOKE_TEST_TARGET_FOLDER:SMOKE_TEST}
  reports-folder: reports
  fingerprint: SHA1:2Fo8c/96zv32xc8GZWbOGYOlRak=
  username: irrelevant
  privateKey: ${FTP_PRIVATE_KEY:}
  publicKey: ${FTP_PUBLIC_KEY:}
  downtime:
    from: ${FTP_DOWNTIME_FROM:23:58}
    to: ${FTP_DOWNTIME_TO:23:59}

# Don't run scheduled tasks unless
# explicitly turned on by tests.
scheduling.enabled: false

tasks:
  upload-letters-interval-ms: ${UPLOAD_LETTERS_INTERVAL:1000}
  # Run every second.
  mark-letters-posted: ${FTP_REPORTS_CRON:*/1 * * * * *}
  stale-letters-report: ${FTP_REPORTS_CRON:*/1 * * * * *}

encryption:
  enabled: ${ENCRYPTION_ENABLED:false}
  publicKey: ${ENCRYPTION_PUBLIC_KEY:}
