java:
  # Don't modify below here
  image: ${IMAGE_NAME}
  ingressHost: ${SERVICE_FQDN}
  memoryRequests: "2Gi"
  cpuRequests: "1000m"
  memoryLimits: "3Gi"
  cpuLimits: "2500m"
  environment:
    # db
    LETTER_TRACKING_DB_HOST: "{{ .Release.Name }}-postgresql"
    LETTER_TRACKING_DB_NAME: "{{ .Values.postgresql.postgresqlDatabase}}"
    LETTER_TRACKING_DB_USER_NAME: "{{ .Values.postgresql.postgresqlUsername}}"
    LETTER_TRACKING_DB_PASSWORD: "{{ .Values.postgresql.postgresqlPassword}}"
    LETTER_TRACKING_DB_CONN_OPTIONS: "?gssEncMode=disable"
    # db - migration
    FLYWAY_URL: "jdbc:postgresql://{{ .Release.Name }}-postgresql:5432/{{ .Values.postgresql.postgresqlDatabase}}"
    FLYWAY_NOOP_STRATEGY: "false"
  postgresql:
    enabled: true
